[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.openssl"]

[phases.build]
cmds = ["echo 'No build step required for PHP'"]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t ." 